module.exports = {
  src: {
    html: 'src/html/pages/**/*.+(html|nunjucks|njk)',
    css: 'src/assets/scss/**/*.scss',
    js: 'src/assets/js/**/*.js',
    images: 'src/assets/images/**/*',
    sprite: 'src/assets/images/sprite/*.svg',
    fonts: 'src/assets/fonts/**/*',
    data: 'src/json/**/*',
    php: 'src/**/*.php',
    app: 'src/app/**/*',
    crm: 'src/crm/**/*',
    phpmailer: 'src/phpmailer/**/*',
  },
  watch: {
    html: 'src/html/**/*.+(html|nunjucks|njk)',
    css: 'src/assets/scss/**/*.scss',
    tailwindcss: './tailwind.config.js',
    js: 'src/assets/js/**/*.js',
    images: 'src/assets/images/**/*',
    sprite: 'src/assets/images/sprite/*.svg',
    fonts: 'src/assets/fonts/**/*',
    data: 'src/json/data.json',
    app: 'src/app/**/*',
    crm: 'src/crm/**/*',
    phpmailer: 'src/phpmailer/**/*',
  },
  build: {
    html: 'build/',
    css: 'build/assets/css/',
    js: 'build/assets/js/',
    fonts: 'build/assets/fonts/',
    images: 'build/assets/images/',
    php: 'build/',
    app: 'build/app/',
    crm: 'build/crm/',
    phpmailer: 'build/phpmailer/',
  },
  clean: 'build/',
};
